/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Bussiness.BChucVu;
import Bussiness.BLinhKienBase;
import Bussiness.BLoaiLinhKien;
import Bussiness.BLoaiThanhVien;
import Bussiness.BNhaCungCap;
import Bussiness.BThanhVien;
import Item.itemBaseLinhKien;
import Item.itemChucVu;
import Item.itemLoaiLinhKien;
import Item.itemLoaiThanhVien;
import Item.itemNhaCungCap;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lvdinh
 */
public class inFormDuLieu extends javax.swing.JInternalFrame {

    /**
     * Creates new form inFormDuLieu
     */
    ArrayList<itemChucVu> lsCV = new ArrayList<>();
    ArrayList<itemLoaiLinhKien> lsLK = new ArrayList<>();
    ArrayList<itemNhaCungCap> lsNCC = new ArrayList<>();
    ArrayList<itemLoaiThanhVien> lsLTV = new ArrayList<>();
    ArrayList<String> lsCombLoaiLK = new ArrayList<>();
    ArrayList<itemBaseLinhKien> lsBLK = new ArrayList<>();
    public inFormDuLieu() {
        initComponents();
        loadCombTenLoaiLK();
        if(this.isVisible()) phanquyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        panelLoaiLK = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableLinhKien = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        textTimLinhKien = new javax.swing.JTextField();
        buttonTimLinhKien = new javax.swing.JButton();
        buttonLamMoiLinhKien = new javax.swing.JButton();
        buttonThemLinhKien = new javax.swing.JButton();
        buttonSuaLinhKien = new javax.swing.JButton();
        buttonXoaLinhKien = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        textGhiChuLinhKien = new javax.swing.JTextArea();
        textTenLoaiLinhKien = new javax.swing.JTextField();
        textMaLoaiLinhKien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonLuuLinhKien = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        panelLK = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tableLK = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        textTimChucVu1 = new javax.swing.JTextField();
        buttonTimChucVu1 = new javax.swing.JButton();
        buttonLamMoiLK = new javax.swing.JButton();
        buttonThemLK = new javax.swing.JButton();
        buttonSuaLK = new javax.swing.JButton();
        buttonXoaLK = new javax.swing.JButton();
        textMaLK = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        buttonLuuLK = new javax.swing.JButton();
        combTenLoaiLK = new javax.swing.JComboBox();
        textTenLK = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        panelChucVu = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableChucVu = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        textTimChucVu = new javax.swing.JTextField();
        buttonTimChucVu = new javax.swing.JButton();
        buttonLamMoiChucVu = new javax.swing.JButton();
        buttonThemChucVu = new javax.swing.JButton();
        buttonSuaChucVu = new javax.swing.JButton();
        buttonXoaChucVu = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        textGhiChuChucVu = new javax.swing.JTextArea();
        textTenChucVu = new javax.swing.JTextField();
        textMaChucVu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        buttonLuuChucVu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelTV = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableThanhVien = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        textTimThanhVien = new javax.swing.JTextField();
        buttonTimLoaiThanhVien = new javax.swing.JButton();
        buttonLamMoiLoaiThanhVien = new javax.swing.JButton();
        buttonThemLoaiThanhVien = new javax.swing.JButton();
        buttonSuaLoaiThanhVien = new javax.swing.JButton();
        buttonXoaLoaiThanhVien = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textGhiChuThanhVien = new javax.swing.JTextArea();
        textTenLoaiThanhVien = new javax.swing.JTextField();
        textMaLoaiThanhVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonLuuLoaiThanhVien = new javax.swing.JButton();
        panelNCC = new javax.swing.JPanel();
        panelNhaCC = new javax.swing.JPanel();
        textEmailNhaCungCap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textMaNhaCungCap = new javax.swing.JTextField();
        textTenNhaCungCap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhaCungCap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textGhiChuNhaCungCap = new javax.swing.JTextArea();
        textDiaChiNhaCungCap = new javax.swing.JTextField();
        textDienThoaiNhaCungCap = new javax.swing.JTextField();
        buttonXoaNhaCungCap = new javax.swing.JButton();
        buttonSuaNhaCungCap = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonThemNhaCungCap = new javax.swing.JButton();
        buttonTimNhaCungCap = new javax.swing.JButton();
        textTimNhaCungCap = new javax.swing.JTextField();
        buttonLuuNhaCungCap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonLamMoiNhaCungCap = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cơ sở dữ liệu");
        setName("DuLieu"); // NOI18N

        tableLinhKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại linh kiện", "Tên loại linh kiện", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLinhKienMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableLinhKien);

        jLabel12.setText("Tìm kiếm");

        buttonTimLinhKien.setText("Tìm kiếm");

        buttonLamMoiLinhKien.setText("Làm mới");
        buttonLamMoiLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiLinhKienActionPerformed(evt);
            }
        });

        buttonThemLinhKien.setText("Thêm");
        buttonThemLinhKien.setActionCommand("Them");
        buttonThemLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemLinhKienActionPerformed(evt);
            }
        });

        buttonSuaLinhKien.setText("Sửa");
        buttonSuaLinhKien.setActionCommand("Sua");
        buttonSuaLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaLinhKienActionPerformed(evt);
            }
        });

        buttonXoaLinhKien.setText("Xóa");
        buttonXoaLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaLinhKienActionPerformed(evt);
            }
        });

        textGhiChuLinhKien.setColumns(20);
        textGhiChuLinhKien.setRows(5);
        jScrollPane6.setViewportView(textGhiChuLinhKien);

        jLabel13.setText("Mã loại linh kiện");

        jLabel14.setText("Tên loại linh kiện");

        jLabel15.setText("Ghi chú");

        buttonLuuLinhKien.setText("Lưu");
        buttonLuuLinhKien.setActionCommand("Luu");
        buttonLuuLinhKien.setEnabled(false);
        buttonLuuLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuLinhKienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoaiLKLayout = new javax.swing.GroupLayout(panelLoaiLK);
        panelLoaiLK.setLayout(panelLoaiLKLayout);
        panelLoaiLKLayout.setHorizontalGroup(
            panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoaiLKLayout.createSequentialGroup()
                .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoaiLKLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textTimLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimLinhKien)
                        .addGap(60, 60, 60)
                        .addComponent(buttonLamMoiLinhKien))
                    .addGroup(panelLoaiLKLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textTenLoaiLinhKien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMaLoaiLinhKien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoaiLKLayout.createSequentialGroup()
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSuaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonThemLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonLuuLinhKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonXoaLinhKien, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelLoaiLKLayout.setVerticalGroup(
            panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoaiLKLayout.createSequentialGroup()
                .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoaiLKLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(textMaLoaiLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(textTenLoaiLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonThemLinhKien)
                            .addComponent(buttonLuuLinhKien))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSuaLinhKien)
                    .addGroup(panelLoaiLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(textTimLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonTimLinhKien)
                        .addComponent(buttonLamMoiLinhKien)
                        .addComponent(buttonXoaLinhKien)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelLoaiLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelLoaiLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại linh kiện", jPanel3);

        tableLK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Loại linh kiện", "Mã linh kiện", "Tên linh kiện"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLKMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tableLK);

        jLabel20.setText("Tìm kiếm");

        buttonTimChucVu1.setText("Tìm kiếm");

        buttonLamMoiLK.setText("Làm mới");
        buttonLamMoiLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiLKActionPerformed(evt);
            }
        });

        buttonThemLK.setText("Thêm");
        buttonThemLK.setActionCommand("Them");
        buttonThemLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemLKActionPerformed(evt);
            }
        });

        buttonSuaLK.setText("Sửa");
        buttonSuaLK.setActionCommand("Sua");
        buttonSuaLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaLKActionPerformed(evt);
            }
        });

        buttonXoaLK.setText("Xóa");
        buttonXoaLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaLKActionPerformed(evt);
            }
        });

        jLabel21.setText("Tên loại");

        jLabel22.setText("Mã linh kiện");

        jLabel23.setText("Tên linh kiện");

        buttonLuuLK.setText("Lưu");
        buttonLuuLK.setActionCommand("Luu");
        buttonLuuLK.setEnabled(false);
        buttonLuuLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuLKActionPerformed(evt);
            }
        });

        combTenLoaiLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combTenLoaiLKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLKLayout = new javax.swing.GroupLayout(panelLK);
        panelLK.setLayout(panelLKLayout);
        panelLKLayout.setHorizontalGroup(
            panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLKLayout.createSequentialGroup()
                .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLKLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(textTimChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimChucVu1)
                        .addGap(60, 60, 60)
                        .addComponent(buttonLamMoiLK))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textMaLK, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLKLayout.createSequentialGroup()
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSuaLK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonThemLK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonLuuLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonXoaLK, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                    .addComponent(combTenLoaiLK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textTenLK))
                .addContainerGap())
        );
        panelLKLayout.setVerticalGroup(
            panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLKLayout.createSequentialGroup()
                .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLKLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(combTenLoaiLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(textMaLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(textTenLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonThemLK)
                            .addComponent(buttonLuuLK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(panelLKLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(panelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textTimChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimChucVu1)
                    .addComponent(buttonLamMoiLK)
                    .addComponent(buttonXoaLK)
                    .addComponent(buttonSuaLK)))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Linh kiện", jPanel8);

        tableChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChucVuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tableChucVu);

        jLabel16.setText("Tìm kiếm");

        buttonTimChucVu.setText("Tìm kiếm");

        buttonLamMoiChucVu.setText("Làm mới");
        buttonLamMoiChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiChucVuActionPerformed(evt);
            }
        });

        buttonThemChucVu.setText("Thêm");
        buttonThemChucVu.setActionCommand("Them");
        buttonThemChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemChucVuActionPerformed(evt);
            }
        });

        buttonSuaChucVu.setText("Sửa");
        buttonSuaChucVu.setActionCommand("Sua");
        buttonSuaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaChucVuActionPerformed(evt);
            }
        });

        buttonXoaChucVu.setText("Xóa");
        buttonXoaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaChucVuActionPerformed(evt);
            }
        });

        textGhiChuChucVu.setColumns(20);
        textGhiChuChucVu.setRows(5);
        jScrollPane8.setViewportView(textGhiChuChucVu);

        jLabel17.setText("Mã chức vụ");

        jLabel18.setText("Tên chức vụ");

        jLabel19.setText("Ghi chú");

        buttonLuuChucVu.setText("Lưu");
        buttonLuuChucVu.setActionCommand("Luu");
        buttonLuuChucVu.setEnabled(false);
        buttonLuuChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChucVuLayout = new javax.swing.GroupLayout(panelChucVu);
        panelChucVu.setLayout(panelChucVuLayout);
        panelChucVuLayout.setHorizontalGroup(
            panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChucVuLayout.createSequentialGroup()
                .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChucVuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(textTimChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimChucVu)
                        .addGap(60, 60, 60)
                        .addComponent(buttonLamMoiChucVu))
                    .addComponent(jScrollPane7))
                .addGap(18, 18, 18)
                .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textTenChucVu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMaChucVu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelChucVuLayout.createSequentialGroup()
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSuaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonThemChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonLuuChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonXoaChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelChucVuLayout.setVerticalGroup(
            panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChucVuLayout.createSequentialGroup()
                .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChucVuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(textMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(textTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonThemChucVu)
                            .addComponent(buttonLuuChucVu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(panelChucVuLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(panelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textTimChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimChucVu)
                    .addComponent(buttonLamMoiChucVu)
                    .addComponent(buttonXoaChucVu)
                    .addComponent(buttonSuaChucVu)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Chức vụ", jPanel2);

        tableThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại thành viên", "Tên loại thành viên", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThanhVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableThanhVien);

        jLabel11.setText("Tìm kiếm");

        buttonTimLoaiThanhVien.setText("Tìm kiếm");

        buttonLamMoiLoaiThanhVien.setText("Làm mới");
        buttonLamMoiLoaiThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiLoaiThanhVienActionPerformed(evt);
            }
        });

        buttonThemLoaiThanhVien.setText("Thêm");
        buttonThemLoaiThanhVien.setActionCommand("Them");
        buttonThemLoaiThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemLoaiThanhVienActionPerformed(evt);
            }
        });

        buttonSuaLoaiThanhVien.setText("Sửa");
        buttonSuaLoaiThanhVien.setActionCommand("Them");
        buttonSuaLoaiThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaLoaiThanhVienActionPerformed(evt);
            }
        });

        buttonXoaLoaiThanhVien.setText("Xóa");

        textGhiChuThanhVien.setColumns(20);
        textGhiChuThanhVien.setRows(5);
        jScrollPane4.setViewportView(textGhiChuThanhVien);

        jLabel8.setText("Mã loại thành viên");

        jLabel9.setText("Tên loại thành viên");

        jLabel10.setText("Ghi chú");

        buttonLuuLoaiThanhVien.setText("Lưu");
        buttonLuuLoaiThanhVien.setActionCommand("Luu");
        buttonLuuLoaiThanhVien.setEnabled(false);
        buttonLuuLoaiThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuLoaiThanhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTVLayout = new javax.swing.GroupLayout(panelTV);
        panelTV.setLayout(panelTVLayout);
        panelTVLayout.setHorizontalGroup(
            panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTVLayout.createSequentialGroup()
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textTimThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimLoaiThanhVien)
                        .addGap(60, 60, 60)
                        .addComponent(buttonLamMoiLoaiThanhVien))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelTVLayout.createSequentialGroup()
                        .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonThemLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSuaLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonXoaLoaiThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(buttonLuuLoaiThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(textTenLoaiThanhVien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMaLoaiThanhVien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelTVLayout.setVerticalGroup(
            panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTVLayout.createSequentialGroup()
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTVLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLuuLoaiThanhVien)))
                .addGap(18, 18, 18)
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textTimThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimLoaiThanhVien)
                    .addComponent(buttonLamMoiLoaiThanhVien)
                    .addComponent(buttonXoaLoaiThanhVien)))
            .addGroup(panelTVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textMaLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textTenLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(buttonThemLoaiThanhVien)
                .addGap(18, 18, 18)
                .addComponent(buttonSuaLoaiThanhVien))
        );

        buttonThemLoaiThanhVien.getAccessibleContext().setAccessibleName("Them");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Loại thành viên", jPanel4);

        jLabel1.setText("Mã nhà cung cấp");

        jLabel3.setText("Địa chỉ");

        jLabel4.setText("Điện thoại");

        jLabel5.setText("Email");

        jLabel6.setText("Ghi chú");

        tableNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Điện thoại", "Email", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhaCungCap);

        textGhiChuNhaCungCap.setColumns(20);
        textGhiChuNhaCungCap.setRows(5);
        jScrollPane2.setViewportView(textGhiChuNhaCungCap);

        buttonXoaNhaCungCap.setText("Xóa");
        buttonXoaNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXoaNhaCungCapMouseClicked(evt);
            }
        });
        buttonXoaNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaNhaCungCapActionPerformed(evt);
            }
        });

        buttonSuaNhaCungCap.setText("Sửa");
        buttonSuaNhaCungCap.setActionCommand("Sua");
        buttonSuaNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaNhaCungCapActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        buttonThemNhaCungCap.setText("Thêm");
        buttonThemNhaCungCap.setActionCommand("Them");
        buttonThemNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemNhaCungCapActionPerformed(evt);
            }
        });

        buttonTimNhaCungCap.setText("Tìm");
        buttonTimNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimNhaCungCapActionPerformed(evt);
            }
        });

        buttonLuuNhaCungCap.setText("Lưu");
        buttonLuuNhaCungCap.setActionCommand("Them");
        buttonLuuNhaCungCap.setEnabled(false);
        buttonLuuNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuNhaCungCapActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên nhà cung cấp");

        buttonLamMoiNhaCungCap.setText("Làm mới");
        buttonLamMoiNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiNhaCungCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNhaCCLayout = new javax.swing.GroupLayout(panelNhaCC);
        panelNhaCC.setLayout(panelNhaCCLayout);
        panelNhaCCLayout.setHorizontalGroup(
            panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhaCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelNhaCCLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNhaCCLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(textTimNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTimNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(buttonLamMoiNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(panelNhaCCLayout.createSequentialGroup()
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDienThoaiNhaCungCap)
                            .addComponent(textEmailNhaCungCap)
                            .addComponent(textTenNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDiaChiNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textMaNhaCungCap)))
                    .addComponent(jLabel6)
                    .addGroup(panelNhaCCLayout.createSequentialGroup()
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonThemNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSuaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonLuuNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonXoaNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelNhaCCLayout.setVerticalGroup(
            panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhaCCLayout.createSequentialGroup()
                .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNhaCCLayout.createSequentialGroup()
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textDiaChiNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textDienThoaiNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textEmailNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSuaNhaCungCap)
                            .addComponent(buttonLuuNhaCungCap))
                        .addGap(18, 18, 18)
                        .addGroup(panelNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonThemNhaCungCap)
                            .addComponent(buttonXoaNhaCungCap)
                            .addComponent(buttonLamMoiNhaCungCap)
                            .addComponent(buttonTimNhaCungCap)
                            .addComponent(textTimNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelNCCLayout = new javax.swing.GroupLayout(panelNCC);
        panelNCC.setLayout(panelNCCLayout);
        panelNCCLayout.setHorizontalGroup(
            panelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNCCLayout.createSequentialGroup()
                .addComponent(panelNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelNCCLayout.setVerticalGroup(
            panelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNCCLayout.createSequentialGroup()
                .addComponent(panelNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Nhà cung cấp", panelNCC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static void phanquyen(){
        switch(formMain.maChucVu){
            case "GD" :
                panelChucVu.setVisible(true);
                panelLK.setVisible(true);
                panelLoaiLK.setVisible(true);
                panelNhaCC.setVisible(true);
                panelTV.setVisible(true);
                break;
            case "Mana":
                panelChucVu.setVisible(false);
                panelLK.setVisible(true);
                panelLoaiLK.setVisible(true);
                panelNhaCC.setVisible(true);
                panelTV.setVisible(false);
                break;
            case "Admin":
                panelChucVu.setVisible(true);
                panelLK.setVisible(false);
                panelLoaiLK.setVisible(false);
                panelNhaCC.setVisible(false);
                panelTV.setVisible(true);
                break;
            default :
                panelChucVu.setVisible(false);
                panelLK.setVisible(false);
                panelLoaiLK.setVisible(false);
                panelNhaCC.setVisible(false);
                panelTV.setVisible(false);
                break;
        }
    }
    private void displayDataChucVu(ResultSet rs){
        DefaultTableModel model=(DefaultTableModel) tableChucVu.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        lsCV.clear();
        try {
            
            while(rs.next()){
                itemChucVu item = new itemChucVu(rs.getString("MaChucVu"), rs.getString("TenChucVu"), rs.getString("GhiChu"));
                lsCV.add(item);
                
                Vector v = new Vector();
                v.add(item.getMaChucVu());
                v.add(item.getTenChucVu());
                v.add(item.getGhiChuChucVu());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void displayLoaiLinhKien(ResultSet rs){
        DefaultTableModel model=(DefaultTableModel) tableLinhKien.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        lsLK.clear();
        try {
            
            while(rs.next()){
                itemLoaiLinhKien item = new itemLoaiLinhKien(rs.getString("MaLoaiLinhKien"), rs.getString("TenLoaiLinhKien"), rs.getString("GhiChu"));
                lsLK.add(item);
                
                Vector v = new Vector();
                v.add(item.getMaLoaiLinhKien());
                v.add(item.getTenLoaiLinhKien());
                v.add(item.getGhiChuLinhKien());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void displayNhaCungCap(ResultSet rs){
        DefaultTableModel model=(DefaultTableModel) tableNhaCungCap.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        lsNCC.clear();
        try {
            
            while(rs.next()){
                itemNhaCungCap item = new itemNhaCungCap(rs.getString("MaNhaCungCap"), rs.getString("TenNhaCungCap"),
                        rs.getString("DiaChiNhaCungCap"), rs.getString("DienThoaiNhaCungCap"), rs.getString("Email"), rs.getString("GhiChu") );
                lsNCC.add(item);
                
                Vector v = new Vector();
                v.add(item.getMaNhaCungCap());
                v.add(item.getTenNhaCungCap());
                v.add(item.getDiaChiNhaCungCap());
                v.add(item.getDienThoaiNhaCungCap());
                v.add(item.getEmail());
                v.add(item.getGhiChu());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void displayLoaiThanhVien(ResultSet rs){
        DefaultTableModel model=(DefaultTableModel) tableThanhVien.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        lsLTV.clear();
        try {
            
            while(rs.next()){
                itemLoaiThanhVien item = new itemLoaiThanhVien(rs.getString("MaLoaiThanhVien"), rs.getString("TenLoaiThanhVien"), rs.getString("GhiChu"));
                lsLTV.add(item);
                
                Vector v = new Vector();
                v.add(item.getMaLoaiThanhVien());
                v.add(item.getTenLoaiThanhVien());
                v.add(item.getGhiChu());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void displayLinhKien(ResultSet rs){
        DefaultTableModel model = (DefaultTableModel) tableLK.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            while(rs.next()){
               
                itemBaseLinhKien item = new itemBaseLinhKien(rs.getString("MaLoaiLinhKien"), rs.getString("MaLinhKien"), rs.getString("TenLinhKien"));
               lsBLK.add(item);
               
                String tenloailinhkien = (new BLoaiLinhKien()).getTenLoaiLinhKien(rs.getString("MaLoaiLinhKien"));
                Vector v = new Vector();
                v.add(tenloailinhkien);
                v.add(rs.getString("MaLinhKien"));
                v.add(rs.getString("TenLinhKien"));
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadCombTenLoaiLK(){
        lsCombLoaiLK.clear();
        combTenLoaiLK.removeAllItems();
        
        BLoaiLinhKien BLLK = new BLoaiLinhKien();
        ResultSet rs = BLLK.getAll();
        try {
            while(rs.next()){
                lsCombLoaiLK.add(rs.getString("MaLoaiLinhKien"));
                combTenLoaiLK.addItem(rs.getString("TenLoaiLinhKien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void buttonLamMoiChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiChucVuActionPerformed
        BChucVu BCV= new BChucVu();
        ResultSet rs=BCV.getAll();
        displayDataChucVu(rs);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLamMoiChucVuActionPerformed

    private void buttonLamMoiLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiLinhKienActionPerformed

        BLoaiLinhKien BLKL = new BLoaiLinhKien();
        ResultSet rs = BLKL.getAll();
        displayLoaiLinhKien(rs);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLamMoiLinhKienActionPerformed

    private void buttonLamMoiLoaiThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiLoaiThanhVienActionPerformed
        // TODO add your handling code here:
        BThanhVien BTV = new BThanhVien();
        ResultSet rs = BTV.getAllThanhVienNative();
        displayLoaiThanhVien(rs);
    }//GEN-LAST:event_buttonLamMoiLoaiThanhVienActionPerformed

    private void buttonLamMoiNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiNhaCungCapActionPerformed
        // TODO add your handling code here:
        BNhaCungCap BNCC = new BNhaCungCap();
        ResultSet rs = BNCC.getAll();
        displayNhaCungCap(rs);
    }//GEN-LAST:event_buttonLamMoiNhaCungCapActionPerformed

    private void buttonThemNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemNhaCungCapActionPerformed
        // TODO add your handling code here:
        if(buttonThemNhaCungCap.getActionCommand().equals("Them")){
            buttonThemNhaCungCap.setActionCommand("Huy");
            buttonThemNhaCungCap.setText("Hủy");

            buttonSuaNhaCungCap.setEnabled(false);
            buttonXoaNhaCungCap.setEnabled(false);

            buttonLuuNhaCungCap.setActionCommand("Them");
            buttonLuuNhaCungCap.setEnabled(true);
        }else{
            buttonThemNhaCungCap.setActionCommand("Them");
            buttonThemNhaCungCap.setText("Thêm");

            buttonSuaNhaCungCap.setEnabled(true);
            buttonXoaNhaCungCap.setEnabled(true);

            buttonLuuNhaCungCap.setActionCommand("Luu");
            buttonLuuNhaCungCap.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonThemNhaCungCapActionPerformed

    private void buttonSuaNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaNhaCungCapActionPerformed
        // TODO add your handling code here:
        if(buttonSuaNhaCungCap.getActionCommand().equals("Sua")){
            buttonSuaNhaCungCap.setActionCommand("Huy");
            buttonSuaNhaCungCap.setText("Hủy");

            buttonThemNhaCungCap.setEnabled(false);
            buttonXoaNhaCungCap.setEnabled(false);

            buttonLuuNhaCungCap.setActionCommand("Sua");
            buttonLuuNhaCungCap.setEnabled(true);
        }else{
            buttonSuaNhaCungCap.setActionCommand("Sua");
            buttonSuaNhaCungCap.setText("Sửa");

            buttonThemNhaCungCap.setEnabled(true);
            buttonXoaNhaCungCap.setEnabled(true);

            buttonLuuNhaCungCap.setActionCommand("Luu");
            buttonLuuNhaCungCap.setEnabled(false);
        }
    }//GEN-LAST:event_buttonSuaNhaCungCapActionPerformed

    private void buttonTimNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTimNhaCungCapActionPerformed

    private void buttonThemChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemChucVuActionPerformed
        // TODO add your handling code here:
        if( buttonThemChucVu.getActionCommand().equals("Them")){
//            textMaChucVu.setText("");
//            textTenChucVu.setText("");
//            textGhiChuChucVu.setText("");
            textMaChucVu.requestFocus();
            
            buttonThemChucVu.setActionCommand("Huy");
            buttonThemChucVu.setText("Hủy");

            buttonSuaChucVu.setEnabled(false);
            buttonXoaChucVu.setEnabled(false);

            buttonLuuChucVu.setActionCommand("Them");
            buttonLuuChucVu.setEnabled(true);
        }else{
            buttonThemChucVu.setActionCommand("Them");
            buttonThemChucVu.setText("Thêm");

            buttonSuaChucVu.setEnabled(true);
            buttonXoaChucVu.setEnabled(true);

            buttonLuuChucVu.setActionCommand("Luu");
            buttonLuuChucVu.setEnabled(false);
        }
    }//GEN-LAST:event_buttonThemChucVuActionPerformed

    private void buttonSuaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaChucVuActionPerformed
         if(buttonSuaChucVu.getActionCommand().equals("Sua")){
            buttonSuaChucVu.setActionCommand("Huy");
            buttonSuaChucVu.setText("Hủy");

            buttonThemChucVu.setEnabled(false);
            buttonXoaChucVu.setEnabled(false);

            buttonLuuChucVu.setActionCommand("Sua");
            buttonLuuChucVu.setEnabled(true);
        }else{
            buttonSuaChucVu.setActionCommand("Sua");
            buttonSuaChucVu.setText("Sửa");

            buttonThemChucVu.setEnabled(true);
            buttonXoaChucVu.setEnabled(true);

            buttonLuuChucVu.setActionCommand("Luu");
            buttonLuuChucVu.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSuaChucVuActionPerformed

    private void buttonThemLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemLinhKienActionPerformed
        if( buttonThemLinhKien.getActionCommand().equals("Them")){
            buttonThemLinhKien.setActionCommand("Huy");
            buttonThemLinhKien.setText("Hủy");

            buttonSuaLinhKien.setEnabled(false);
            buttonXoaLinhKien.setEnabled(false);

            buttonLuuLinhKien.setActionCommand("Them");
            buttonLuuLinhKien.setEnabled(true);
        }else{
            buttonThemLinhKien.setActionCommand("Them");
            buttonThemLinhKien.setText("Thêm");

            buttonSuaLinhKien.setEnabled(true);
            buttonXoaLinhKien.setEnabled(true);

            buttonLuuLinhKien.setActionCommand("Luu");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonThemLinhKienActionPerformed

    private void buttonSuaLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaLinhKienActionPerformed
         if(buttonSuaLinhKien.getActionCommand().equals("Sua")){
            buttonSuaLinhKien.setActionCommand("Huy");
            buttonSuaLinhKien.setText("Hủy");

            buttonThemLinhKien.setEnabled(false);
            buttonXoaLinhKien.setEnabled(false);

            buttonLuuLinhKien.setActionCommand("Sua");
            buttonLuuLinhKien.setEnabled(true);
        }else{
            buttonSuaLinhKien.setActionCommand("Sua");
            buttonSuaLinhKien.setText("Sửa");

            buttonThemLinhKien.setEnabled(true);
            buttonXoaLinhKien.setEnabled(true);

            buttonLuuLinhKien.setActionCommand("Luu");
            buttonLuuLinhKien.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSuaLinhKienActionPerformed

    private void buttonThemLoaiThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemLoaiThanhVienActionPerformed
        if( buttonThemLoaiThanhVien.getActionCommand().equals("Them")){
            buttonThemLoaiThanhVien.setActionCommand("Huy");
            buttonThemLoaiThanhVien.setText("Hủy");

            buttonSuaLoaiThanhVien.setEnabled(false);
            buttonXoaLoaiThanhVien.setEnabled(false);

            buttonLuuLoaiThanhVien.setActionCommand("Them");
            buttonLuuLoaiThanhVien.setEnabled(true);
        }else{
            buttonThemLoaiThanhVien.setActionCommand("Them");
            buttonThemLoaiThanhVien.setText("Thêm");

            buttonSuaLoaiThanhVien.setEnabled(true);
            buttonXoaLoaiThanhVien.setEnabled(true);

            buttonLuuLoaiThanhVien.setActionCommand("Luu");
            buttonLuuLoaiThanhVien.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonThemLoaiThanhVienActionPerformed

    private void buttonSuaLoaiThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaLoaiThanhVienActionPerformed
        if(buttonSuaLoaiThanhVien.getActionCommand().equals("Sua")){
            buttonSuaLoaiThanhVien.setActionCommand("Huy");
            buttonSuaLoaiThanhVien.setText("Hủy");

            buttonThemLoaiThanhVien.setEnabled(false);
            buttonXoaLoaiThanhVien.setEnabled(false);

            buttonLuuLoaiThanhVien.setActionCommand("Sua");
            buttonLuuLoaiThanhVien.setEnabled(true);
        }else{
            buttonSuaLoaiThanhVien.setActionCommand("Sua");
            buttonSuaLoaiThanhVien.setText("Sửa");

            buttonThemLoaiThanhVien.setEnabled(true);
            buttonXoaLoaiThanhVien.setEnabled(true);

            buttonLuuLoaiThanhVien.setActionCommand("Luu");
            buttonLuuLoaiThanhVien.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSuaLoaiThanhVienActionPerformed

    private void buttonLuuChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuChucVuActionPerformed
        if(buttonLuuChucVu.getActionCommand().equals("Them")){
            
            //them
            BChucVu BCV = new BChucVu();
            if(BCV.insertByProperties(textMaChucVu.getText(), textTenChucVu.getText(), textGhiChuChucVu.getText())){
               // JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Chưa thêm!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuChucVu.setActionCommand("Luu");
            buttonLuuChucVu.setEnabled(false);
            
            buttonThemChucVu.setText("Thêm");
            buttonThemChucVu.setActionCommand("Them");
            
            buttonSuaChucVu.setEnabled(true);
            
            buttonXoaChucVu.setEnabled(true);
        }
        else if(buttonLuuChucVu.getActionCommand().equals("Sua")){
            //them
            BChucVu BCV = new BChucVu();
            if(BCV.updateBySQLString(textMaChucVu.getText(), textTenChucVu.getText(), textGhiChuChucVu.getText())){
                JOptionPane.showMessageDialog(this, "Thêm sửa thành công!", "Đã sửa!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi sửa!", "Chưa sửa!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuChucVu.setActionCommand("Luu");
            buttonLuuChucVu.setEnabled(false);
            
            buttonSuaChucVu.setText("Sửa");
            buttonSuaChucVu.setActionCommand("Sua");
            
            buttonThemChucVu.setEnabled(true);
            
            buttonXoaChucVu.setEnabled(true);
        }
        buttonLamMoiChucVuActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLuuChucVuActionPerformed

    private void tableChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChucVuMouseClicked
        int index=tableChucVu.getSelectedRow();
        if(index>=0){
            textMaChucVu.setText(lsCV.get(index).getMaChucVu());
            textTenChucVu.setText(lsCV.get(index).getTenChucVu());
            textGhiChuChucVu.setText(lsCV.get(index).getGhiChuChucVu());
            
            
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableChucVuMouseClicked

    private void buttonXoaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaChucVuActionPerformed
        // TODO add your handling code here:
        int index=tableChucVu.getSelectedRow();
        if(index<0)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng có dữ liệu!", "Rỗng!", JOptionPane.ERROR_MESSAGE);
        else{
            if(0==JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa", JOptionPane.OK_CANCEL_OPTION)){
                BChucVu BCV=new BChucVu();
                String machucvu=lsCV.get(index).getMaChucVu();
                
                if(BCV.deleteByID(machucvu)){
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công!", "Đã xóa!", JOptionPane.INFORMATION_MESSAGE);
                    buttonLamMoiChucVuActionPerformed(evt);
                }else
                    JOptionPane.showMessageDialog(this, "Có lỗi trong khi xóa!","Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonXoaChucVuActionPerformed

    private void buttonLuuLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuLinhKienActionPerformed
        // TODO add your handling code here:
        if(buttonLuuLinhKien.getActionCommand().equals("Them")){
            
            //them
            BLoaiLinhKien BLLK= new BLoaiLinhKien();
            if(BLLK.insertByProperties(textMaLoaiLinhKien.getText(), textTenLoaiLinhKien.getText(), textGhiChuLinhKien.getText())){
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Chưa thêm!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLinhKien.setActionCommand("Luu");
            buttonLuuLinhKien.setEnabled(false);
            
            buttonThemLinhKien.setText("Thêm");
            buttonThemLinhKien.setActionCommand("Them");
            
            buttonSuaLinhKien.setEnabled(true);
            
            buttonXoaLinhKien.setEnabled(true);
        }
        else if(buttonLuuLinhKien.getActionCommand().equals("Sua")){
            //them
            BLoaiLinhKien BLLK= new BLoaiLinhKien();
            if(BLLK.updateByProperties(textMaLoaiLinhKien.getText(), textTenLoaiLinhKien.getText(), textGhiChuLinhKien.getText())){
                JOptionPane.showMessageDialog(this, "Thêm sửa thành công!", "Đã sửa!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi sửa!", "Chưa sửa!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLinhKien.setActionCommand("Luu");
            buttonLuuLinhKien.setEnabled(false);
            
            buttonSuaLinhKien.setText("Sửa");
            buttonSuaLinhKien.setActionCommand("Sua");
            
            buttonThemLinhKien.setEnabled(true);
            
            buttonXoaLinhKien.setEnabled(true);
        }
        buttonLamMoiLinhKienActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLuuLinhKienActionPerformed

    private void buttonXoaLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaLinhKienActionPerformed
        // TODO add your handling code here:
         int index=tableLinhKien.getSelectedRow();
        if(index<0)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng có dữ liệu!", "Rỗng!", JOptionPane.ERROR_MESSAGE);
        else{
            if(0==JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa", JOptionPane.OK_CANCEL_OPTION)){
               BLoaiLinhKien BLLK = new BLoaiLinhKien();
                String maloailinhkien=lsLK.get(index).getMaLoaiLinhKien();
                
                if(BLLK.deleteByID(maloailinhkien)){
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công!", "Đã xóa!", JOptionPane.INFORMATION_MESSAGE);
                    buttonLamMoiChucVuActionPerformed(evt);
                }else
                    JOptionPane.showMessageDialog(this, "Có lỗi trong khi xóa!","Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonXoaLinhKienActionPerformed

    private void tableLinhKienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLinhKienMouseClicked

        int index=tableLinhKien.getSelectedRow();
        if(index>=0){
            textMaLoaiLinhKien.setText(lsLK.get(index).getMaLoaiLinhKien());
            textTenLoaiLinhKien.setText(lsLK.get(index).getTenLoaiLinhKien());
            textGhiChuLinhKien.setText(lsLK.get(index).getGhiChuLinhKien());
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_tableLinhKienMouseClicked

    private void buttonLuuLoaiThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuLoaiThanhVienActionPerformed
        if(buttonLuuLoaiThanhVien.getActionCommand().equals("Them")){
            
            //them
            BLoaiThanhVien BLTV=new BLoaiThanhVien();
            if(BLTV.insertByProperties(textMaLoaiThanhVien.getText(), textTenLoaiThanhVien.getText(), textGhiChuThanhVien.getText())){
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Chưa thêm!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLoaiThanhVien.setActionCommand("Luu");
            buttonLuuLoaiThanhVien.setEnabled(false);
            
            buttonThemLoaiThanhVien.setText("Thêm");
            buttonThemLoaiThanhVien.setActionCommand("Them");
            
            buttonSuaLoaiThanhVien.setEnabled(true);
            
            buttonXoaLoaiThanhVien.setEnabled(true);
        }
        else if(buttonLuuLoaiThanhVien.getActionCommand().equals("Sua")){
            //them
            BLoaiThanhVien BLTV=new BLoaiThanhVien();
            if(BLTV.updateByProperties(textMaLoaiThanhVien.getText(), textTenLoaiThanhVien.getText(), textGhiChuThanhVien.getText())){
                JOptionPane.showMessageDialog(this, "Thêm sửa thành công!", "Đã sửa!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi sửa!", "Chưa sửa!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLoaiThanhVien.setActionCommand("Luu");
            buttonLuuLoaiThanhVien.setEnabled(false);
            
            buttonSuaLoaiThanhVien.setText("Sửa");
            buttonSuaLoaiThanhVien.setActionCommand("Sua");
            
            buttonThemLoaiThanhVien.setEnabled(true);
            
            buttonXoaLoaiThanhVien.setEnabled(true);
        }
        buttonLamMoiLoaiThanhVienActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLuuLoaiThanhVienActionPerformed

    private void tableThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThanhVienMouseClicked
        // TODO add your handling code here:
        int index=tableThanhVien.getSelectedRow();
        if(index>=0){
            textMaLoaiThanhVien.setText(lsLTV.get(index).getMaLoaiThanhVien());
            textTenLoaiThanhVien.setText(lsLTV.get(index).getTenLoaiThanhVien());
            textGhiChuThanhVien.setText(lsLTV.get(index).getGhiChu());
            
            
        }
    }//GEN-LAST:event_tableThanhVienMouseClicked

    private void buttonLuuNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuNhaCungCapActionPerformed
        // TODO add your handling code here:
        if(buttonLuuNhaCungCap.getActionCommand().equals("Them")){
            
            //them
            BNhaCungCap BNCC = new BNhaCungCap();
            if(BNCC.insertByProperties(textMaNhaCungCap.getText(), textTenNhaCungCap.getText(),textDiaChiNhaCungCap.getText(),
                    textDienThoaiNhaCungCap.getText(), textEmailNhaCungCap.getText(),textGhiChuNhaCungCap.getText())){
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Chưa thêm!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuNhaCungCap.setActionCommand("Luu");
            buttonLuuNhaCungCap.setEnabled(false);
            
            buttonThemNhaCungCap.setText("Thêm");
            buttonThemNhaCungCap.setActionCommand("Them");
            
            buttonSuaNhaCungCap.setEnabled(true);
            
            buttonXoaNhaCungCap.setEnabled(true);
        }
        else if(buttonLuuNhaCungCap.getActionCommand().equals("Sua")){
            //them
            BNhaCungCap BNCC = new BNhaCungCap();
            if(BNCC.updateByProperties(textMaNhaCungCap.getText(), textTenNhaCungCap.getText(),textDiaChiNhaCungCap.getText(),
                    textDienThoaiNhaCungCap.getText(), textEmailNhaCungCap.getText(),textGhiChuNhaCungCap.getText())){
                JOptionPane.showMessageDialog(this, "Thêm sửa thành công!", "Đã sửa!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi sửa!", "Chưa sửa!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuNhaCungCap.setActionCommand("Luu");
            buttonLuuNhaCungCap.setEnabled(false);
            
            buttonSuaNhaCungCap.setText("Sửa");
            buttonSuaNhaCungCap.setActionCommand("Sua");
            
            buttonThemNhaCungCap.setEnabled(true);
            
            buttonXoaNhaCungCap.setEnabled(true);
        }
        buttonLamMoiNhaCungCapActionPerformed(evt);
    }//GEN-LAST:event_buttonLuuNhaCungCapActionPerformed

    private void buttonXoaNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXoaNhaCungCapMouseClicked

       //ling code here:
    }//GEN-LAST:event_buttonXoaNhaCungCapMouseClicked

    private void buttonXoaNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaNhaCungCapActionPerformed
        // TODO add your handling code here:
         int index=tableNhaCungCap.getSelectedRow();
        if(index<0)
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng có dữ liệu!", "Rỗng!", JOptionPane.ERROR_MESSAGE);
        else{
            if(0==JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa", JOptionPane.OK_CANCEL_OPTION)){
                BNhaCungCap BNCC = new BNhaCungCap();
                String machucvu=lsNCC.get(index).getMaNhaCungCap();
                
                if(BNCC.deleteByID(machucvu)){
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công!", "Đã xóa!", JOptionPane.INFORMATION_MESSAGE);
                    buttonLamMoiNhaCungCapActionPerformed(evt);
                }else
                    JOptionPane.showMessageDialog(this, "Có lỗi trong khi xóa!","Lỗi!", JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your hand
    }//GEN-LAST:event_buttonXoaNhaCungCapActionPerformed

    private void tableNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhaCungCapMouseClicked
        int index=tableNhaCungCap.getSelectedRow();
        if(index>=0){
            textMaNhaCungCap.setText(lsNCC.get(index).getMaNhaCungCap());
            textTenNhaCungCap.setText(lsNCC.get(index).getTenNhaCungCap());
            textGhiChuNhaCungCap.setText(lsNCC.get(index).getGhiChu());
            
            textDiaChiNhaCungCap.setText(lsNCC.get(index).getDiaChiNhaCungCap());
            textEmailNhaCungCap.setText(lsNCC.get(index).getEmail());
            textDienThoaiNhaCungCap.setText(lsNCC.get(index).getDienThoaiNhaCungCap());
            buttonLamMoiLoaiThanhVienActionPerformed(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNhaCungCapMouseClicked

    private void tableLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLKMouseClicked
        // TODO add your handling code here:
        int index=tableLK.getSelectedRow();
        if(index>=0){
            String tenloailinhkien = (new BLoaiLinhKien()).getTenLoaiLinhKien(lsBLK.get(index).getMaLoaiLinhKien());
            combTenLoaiLK.setSelectedItem(tenloailinhkien);
            
            textMaLK.setText(lsBLK.get(index).getMaLinhkien());
            textTenLK.setText(lsBLK.get(index).getTenLinhKien());
   
        }
    }//GEN-LAST:event_tableLKMouseClicked

    private void buttonLamMoiLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiLKActionPerformed
        // TODO add your handling code here:
        BLinhKienBase BLKB = new BLinhKienBase();
        ResultSet rs = BLKB.getBaseProperties();
        displayLinhKien(rs);
        loadCombTenLoaiLK();
    }//GEN-LAST:event_buttonLamMoiLKActionPerformed

    private void buttonThemLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemLKActionPerformed
        // TODO add your handling code here:
           if( buttonThemLK.getActionCommand().equals("Them")){
            buttonThemLK.setActionCommand("Huy");
            buttonThemLK.setText("Hủy");

            buttonSuaLK.setEnabled(false);
            buttonXoaLK.setEnabled(false);

            buttonLuuLK.setActionCommand("Them");
            buttonLuuLK.setEnabled(true);
        }else{
            buttonThemLK.setActionCommand("Them");
            buttonThemLK.setText("Thêm");

            buttonSuaLK.setEnabled(true);
            buttonXoaLK.setEnabled(true);

            buttonLuuLK.setActionCommand("Luu");
            buttonLuuLK.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonThemLKActionPerformed

    private void buttonSuaLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaLKActionPerformed
         if(buttonSuaLK.getActionCommand().equals("Sua")){
            buttonSuaLK.setActionCommand("Huy");
            buttonSuaLK.setText("Hủy");

            buttonThemLK.setEnabled(false);
            buttonXoaLK.setEnabled(false);

            buttonLuuLK.setActionCommand("Sua");
            buttonLuuLK.setEnabled(true);
        }else{
            buttonSuaLK.setActionCommand("Sua");
            buttonSuaLK.setText("Sửa");

            buttonThemLK.setEnabled(true);
            buttonXoaLK.setEnabled(true);

            buttonLuuLK.setActionCommand("Luu");
            buttonLuuLK.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_buttonSuaLKActionPerformed

    private void buttonXoaLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaLKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXoaLKActionPerformed

    private void buttonLuuLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuLKActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        BLoaiLinhKien BLLK = new BLoaiLinhKien();
            //String maloailinhkien = BLLK.getMaLoaiLinhKien(combTenLoaiLK.getSelectedItem().toString());
        String maloailinhkien = lsCombLoaiLK.get(combTenLoaiLK.getSelectedIndex());
        if(buttonLuuLK.getActionCommand().equals("Them")){
            
            //them
            
                    
            BLinhKienBase BLKB = new BLinhKienBase();
            if(BLKB.insertBaseProperties(maloailinhkien, textMaLK.getText(),textTenLK.getText())){
                //JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm!", JOptionPane.INFORMATION_MESSAGE);
                buttonLamMoiLKActionPerformed(evt);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Chưa thêm!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLK.setActionCommand("Luu");
            buttonLuuLK.setEnabled(false);
            
            buttonThemLK.setText("Thêm");
            buttonThemLK.setActionCommand("Them");
            
            buttonSuaLK.setEnabled(true);
            
            buttonXoaLK.setEnabled(true);
        }
        else if(buttonLuuLK.getActionCommand().equals("Sua")){
            //them
            BLinhKienBase BLKB = new BLinhKienBase();
            
            if(BLKB.updateBaseProperties(maloailinhkien, textMaLK.getText(),textTenLK.getText())){
                //JOptionPane.showMessageDialog(this, "Thêm sửa thành công!", "Đã sửa!", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi sửa!", "Chưa sửa!", JOptionPane.ERROR_MESSAGE);
            
            //-them
            buttonLuuLK.setActionCommand("Luu");
            buttonLuuLK.setEnabled(false);
            
            buttonSuaLK.setText("Sửa");
            buttonSuaLK.setActionCommand("Sua");
            
            buttonThemLK.setEnabled(true);
            
            buttonXoaLK.setEnabled(true);
        }
    }//GEN-LAST:event_buttonLuuLKActionPerformed

    private void combTenLoaiLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combTenLoaiLKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTenLoaiLKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLamMoiChucVu;
    private javax.swing.JButton buttonLamMoiLK;
    private javax.swing.JButton buttonLamMoiLinhKien;
    private javax.swing.JButton buttonLamMoiLoaiThanhVien;
    private javax.swing.JButton buttonLamMoiNhaCungCap;
    private javax.swing.JButton buttonLuuChucVu;
    private javax.swing.JButton buttonLuuLK;
    private javax.swing.JButton buttonLuuLinhKien;
    private javax.swing.JButton buttonLuuLoaiThanhVien;
    private javax.swing.JButton buttonLuuNhaCungCap;
    private javax.swing.JButton buttonSuaChucVu;
    private javax.swing.JButton buttonSuaLK;
    private javax.swing.JButton buttonSuaLinhKien;
    private javax.swing.JButton buttonSuaLoaiThanhVien;
    private javax.swing.JButton buttonSuaNhaCungCap;
    private javax.swing.JButton buttonThemChucVu;
    private javax.swing.JButton buttonThemLK;
    private javax.swing.JButton buttonThemLinhKien;
    private javax.swing.JButton buttonThemLoaiThanhVien;
    private javax.swing.JButton buttonThemNhaCungCap;
    private javax.swing.JButton buttonTimChucVu;
    private javax.swing.JButton buttonTimChucVu1;
    private javax.swing.JButton buttonTimLinhKien;
    private javax.swing.JButton buttonTimLoaiThanhVien;
    private javax.swing.JButton buttonTimNhaCungCap;
    private javax.swing.JButton buttonXoaChucVu;
    private javax.swing.JButton buttonXoaLK;
    private javax.swing.JButton buttonXoaLinhKien;
    private javax.swing.JButton buttonXoaLoaiThanhVien;
    private javax.swing.JButton buttonXoaNhaCungCap;
    private javax.swing.JComboBox combTenLoaiLK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JPanel panelChucVu;
    protected static javax.swing.JPanel panelLK;
    protected static javax.swing.JPanel panelLoaiLK;
    protected static javax.swing.JPanel panelNCC;
    protected static javax.swing.JPanel panelNhaCC;
    static javax.swing.JPanel panelTV;
    private javax.swing.JTable tableChucVu;
    private javax.swing.JTable tableLK;
    private javax.swing.JTable tableLinhKien;
    private javax.swing.JTable tableNhaCungCap;
    private javax.swing.JTable tableThanhVien;
    private javax.swing.JTextField textDiaChiNhaCungCap;
    private javax.swing.JTextField textDienThoaiNhaCungCap;
    private javax.swing.JTextField textEmailNhaCungCap;
    private javax.swing.JTextArea textGhiChuChucVu;
    private javax.swing.JTextArea textGhiChuLinhKien;
    private javax.swing.JTextArea textGhiChuNhaCungCap;
    private javax.swing.JTextArea textGhiChuThanhVien;
    private javax.swing.JTextField textMaChucVu;
    private javax.swing.JTextField textMaLK;
    private javax.swing.JTextField textMaLoaiLinhKien;
    private javax.swing.JTextField textMaLoaiThanhVien;
    private javax.swing.JTextField textMaNhaCungCap;
    private javax.swing.JTextField textTenChucVu;
    private javax.swing.JTextField textTenLK;
    private javax.swing.JTextField textTenLoaiLinhKien;
    private javax.swing.JTextField textTenLoaiThanhVien;
    private javax.swing.JTextField textTenNhaCungCap;
    private javax.swing.JTextField textTimChucVu;
    private javax.swing.JTextField textTimChucVu1;
    private javax.swing.JTextField textTimLinhKien;
    private javax.swing.JTextField textTimNhaCungCap;
    private javax.swing.JTextField textTimThanhVien;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableDisplay() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
