/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Bussiness.BNhaCungCap;
import Bussiness.BNhanVien;
import Bussiness.BPhieuDatHang;
import Bussiness.BSanPham;
import Item.itemPhieuDatHang;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lvdinh
 */
public class inFormPhieuDatHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form inFormPhieuNhap
     */
    ArrayList<itemPhieuDatHang> lsPDH=new ArrayList<>();
    ArrayList<String> lsCombNhaCungCap= new ArrayList<>();
    ArrayList<String> lsCombNhanVien = new ArrayList<>();
    ArrayList<String> lsCombMaLinhKien = new ArrayList<>();
    public inFormPhieuDatHang() {
        initComponents();
        loadCombNhaCungCap();
        loadCombNhanVien();
        loadCombMaLinhKien();
        
        
        textTimKiem.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                //System.out.println("removeUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                //System.out.println("insertUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //System.out.println("changedUpdate");
                buttonTimKiemActionPerformed(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuDatHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietPhieuDatHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftextMaPhieuDatHang = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonLamMoi = new javax.swing.JButton();
        buttonTimKiem = new javax.swing.JButton();
        textTimKiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radPhieu = new javax.swing.JRadioButton();
        radChiTietPhieu = new javax.swing.JRadioButton();
        buttonOK = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonThem = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combTenNhanVien = new javax.swing.JComboBox();
        combNhaCungCap = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        combMaLinhKien = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        buttonCong = new javax.swing.JButton();
        textNgayLapPhieu = new javax.swing.JTextField();
        buttonTru = new javax.swing.JButton();
        labelTenPhieu = new javax.swing.JLabel();
        buttonX = new javax.swing.JButton();

        setClosable(true);
        setTitle("Phiếu đặt hàng");
        setName("PhieuDatHang"); // NOI18N

        tablePhieuDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu đặt hàng", "Nhà cung cấp", "Tên nhân viên lập phiếu đặt hàng", "Ngày lập phiếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhieuDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuDatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuDatHang);

        tableChiTietPhieuDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã linh kiện", "Tên linh kiện", "Số lượng đã đặt", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableChiTietPhieuDatHang);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chi tiết phiếu đặt hàng");

        jLabel2.setText("Mã phiếu đặt hàng");

        try {
            ftextMaPhieuDatHang.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("PD####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftextMaPhieuDatHang.setText("PD");
        ftextMaPhieuDatHang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ftextMaPhieuDatHangInputMethodTextChanged(evt);
            }
        });

        jLabel4.setText("Tên nhân viên");

        jLabel5.setText("Ngày lập phiếu");

        buttonLamMoi.setText("Làm mới");
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        buttonTimKiem.setText("Tìm kiếm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm");

        buttonGroup1.add(radPhieu);
        radPhieu.setSelected(true);
        radPhieu.setText("Phiếu đặt hàng");

        buttonGroup1.add(radChiTietPhieu);
        radChiTietPhieu.setText("Chi tiết phiếu đặt hàng");
        radChiTietPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radChiTietPhieuActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonXoa.setText("Xóa");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        buttonThem.setText("Thêm");
        buttonThem.setActionCommand("Them");
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });

        buttonSua.setText("Sửa");
        buttonSua.setActionCommand("Sua");
        buttonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhà cung cấp");

        jButton1.setText("Mới");

        jLabel7.setText("Mã linh kiện");

        jLabel8.setText("Số lượng");

        spinSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        buttonCong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonCong.setForeground(new java.awt.Color(51, 255, 51));
        buttonCong.setText("+");
        buttonCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCongActionPerformed(evt);
            }
        });

        buttonTru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTru.setForeground(new java.awt.Color(255, 204, 0));
        buttonTru.setText("-");
        buttonTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTruActionPerformed(evt);
            }
        });

        labelTenPhieu.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelTenPhieu.setForeground(new java.awt.Color(0, 0, 204));

        buttonX.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        buttonX.setForeground(new java.awt.Color(204, 0, 0));
        buttonX.setText("X");
        buttonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combMaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(buttonCong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radChiTietPhieu)
                                            .addComponent(radPhieu))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonTru)
                                        .addGap(29, 29, 29)
                                        .addComponent(buttonX)
                                        .addGap(11, 11, 11))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(buttonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(combTenNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ftextMaPhieuDatHang)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(combNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textNgayLapPhieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelTenPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(radChiTietPhieu))
                        .addComponent(radPhieu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTenPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftextMaPhieuDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSua, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(buttonThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(buttonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combMaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCong)
                    .addComponent(buttonTru)
                    .addComponent(buttonX))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayDataPhieuDatHang(ResultSet rs){
        lsPDH.clear();
        DefaultTableModel model = (DefaultTableModel) tablePhieuDatHang.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                itemPhieuDatHang item = new itemPhieuDatHang(rs.getString("MaPhieuDatHang"), rs.getString("TenNhaCungCap"),
                         rs.getString("TenNhanVienDatHang"),rs.getString("NgayLapPhieuDatHang"));
                lsPDH.add(item);
                
                Vector vector = new Vector();
                vector.add(item.getMaPhieuDatHang());
                vector.add(item.getTenNhaCungCap());
                
                vector.add(item.getTenNhanVienDatHang());
                vector.add(item.getNgayLapPhieuDatHang());
                
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataPhieuNhap 2: " + ex.getMessage());
        }
    }
    private void displayDataChiTietPhieuNhap(ResultSet rs){
        DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuDatHang.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                
                Vector vector = new Vector();
                
                vector.add(rs.getString("MaLinhKien"));
                vector.add(rs.getString("TenLinhKien"));
                
                vector.add(rs.getString("SoLuong"));
                vector.add(rs.getBigDecimal("DonGia"));
                
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataChiTietPhieuNhap 2: " + ex.getMessage());
        }
    }
    private void loadCombNhaCungCap(){
        combNhaCungCap.removeAllItems();
        lsCombNhaCungCap.clear();
        BNhaCungCap BNCC = new BNhaCungCap();
        ResultSet rs = BNCC.getAll();
        try {
            while(rs.next()){
                combNhaCungCap.addItem(rs.getString("TenNhaCungCap"));
                lsCombNhaCungCap.add(rs.getString("MaNhaCungCap"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuDatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadCombNhanVien(){
         combTenNhanVien.removeAllItems();
        lsCombNhanVien.clear();
        BNhanVien BNV = new BNhanVien();
        ResultSet rs = BNV.getAllNhanVienXN();
        try {
            while(rs.next()){
                combTenNhanVien.addItem(rs.getString("TenNhanVien"));
                lsCombNhanVien.add(rs.getString("MaNhanVien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuDatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadCombMaLinhKien(){
         combMaLinhKien.removeAllItems();
        lsCombMaLinhKien.clear();
        BSanPham BSP=new  BSanPham();
        ResultSet rs = BSP.getAllMaLinhKien();
        try {
            while(rs.next()){
                combMaLinhKien.addItem(rs.getString("MaLinhKien"));
                lsCombMaLinhKien.add(rs.getString("TenLinhKien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuDatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void radChiTietPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radChiTietPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radChiTietPhieuActionPerformed

    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        BPhieuDatHang BPDH=new BPhieuDatHang();
        ResultSet rs=BPDH.getAll();
        displayDataPhieuDatHang(rs);
        tableChiTietPhieuDatHang.removeAll();
        
        
        
        loadCombNhaCungCap();
        loadCombNhanVien();
        loadCombMaLinhKien();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLamMoiActionPerformed

    private void tablePhieuDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuDatHangMouseClicked
        int index=tablePhieuDatHang.getSelectedRow();
        
        String maphieudat=lsPDH.get(index).getMaPhieuDatHang();
        
        labelTenPhieu.setText(maphieudat);
        
        BPhieuDatHang BPD = new BPhieuDatHang();
        ResultSet rs=BPD.getChiTietPhieuDatHang(maphieudat);
        displayDataChiTietPhieuNhap(rs);
        
        ftextMaPhieuDatHang.setText(lsPDH.get(index).getMaPhieuDatHang());
        
        combNhaCungCap.setSelectedItem(lsPDH.get(index).getTenNhaCungCap());
        combTenNhanVien.setSelectedItem(lsPDH.get(index).getTenNhanVienDatHang());
        textNgayLapPhieu.setText(lsPDH.get(index).getNgayLapPhieuDatHang());
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePhieuDatHangMouseClicked

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        BPhieuDatHang BPDH = new BPhieuDatHang();
        
        if(BPDH.insertByProperties(ftextMaPhieuDatHang.getText(), lsCombNhaCungCap.get(combNhaCungCap.getSelectedIndex()),
                lsCombNhanVien.get(combTenNhanVien.getSelectedIndex()),textNgayLapPhieu.getText())){
          //  JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm", JOptionPane.INFORMATION_MESSAGE);
            buttonLamMoiActionPerformed(evt);
        }
        else
            JOptionPane.showMessageDialog(this,"Xảy ra lỗi khi thêm!", "Chưa thêm!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonThemActionPerformed

    private void buttonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaActionPerformed
         int index=tablePhieuDatHang.getSelectedRow();
         String manhacungcap = lsCombNhaCungCap.get(combNhaCungCap.getSelectedIndex());
         String manhanvien = lsCombNhanVien.get(combTenNhanVien.getSelectedIndex());
         String ngaylapphieu = lsPDH.get(index).getNgayLapPhieuDatHang();
         String maphieudat = lsPDH.get(index).getMaPhieuDatHang();
         
         BPhieuDatHang BPDH = new BPhieuDatHang();
         if(BPDH.updateByProperties(maphieudat, manhacungcap, manhanvien, ngaylapphieu)){
            // JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Đã cập nhật!", JOptionPane.INFORMATION_MESSAGE);
             buttonLamMoiActionPerformed(evt);
         }
         
         else
             JOptionPane.showMessageDialog(this, "Xảy ra lỗi trong khi cập nhật!", "Chưa cập nhật!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonSuaActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCongActionPerformed
        String malinhkien = combMaLinhKien.getSelectedItem().toString();
        if(!malinhkien.isEmpty()){
            int index =tablePhieuDatHang.getSelectedRow();
            
            String maphieudathang = lsPDH.get(index).getMaPhieuDatHang();
            BPhieuDatHang BPDH = new BPhieuDatHang();
            int soluong = (int)spinSoLuong.getValue();
            if(soluong>0 && BPDH.insertChiTietPhieuDatHang(maphieudathang, malinhkien, soluong, BigDecimal.ONE)){

                 ResultSet rs=BPDH.getChiTietPhieuDatHang(maphieudathang);
                 displayDataChiTietPhieuNhap(rs);
            }
                //JOptionPane.showMessageDialog(this, "Them", "them", JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this, "Lỗi khi thêm linh kiện!", "Lỗi!", JOptionPane.INFORMATION_MESSAGE);
                //tablePhieuDatHangMouseClicked(null);
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCongActionPerformed

    @SuppressWarnings("empty-statement")
    private void buttonTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTruActionPerformed
        // TODO add your handling code here:
        int index = tableChiTietPhieuDatHang.getSelectedRow();
        if(index>=0){
           DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuDatHang.getModel();
           String malinhkien = model.getValueAt(index, 0).toString();
           Object soluong =  model.getValueAt(index, 2);
           //System.out.print("-"+soluong);
           int i=Integer.valueOf((String)soluong)-(int)spinSoLuong.getValue();
           if(i>=0){
               //giam so luong di 1
               int index2 = tablePhieuDatHang.getSelectedRow();
               if(index2>=0){
                   String maphieudathang=lsPDH.get(index2).getMaPhieuDatHang();
                   BPhieuDatHang BPDH = new BPhieuDatHang();
                   if(BPDH.updateSoLuongChiTietPhieuDatHang(maphieudathang, malinhkien, i)){
                       //reload
                        BPhieuDatHang BPD = new BPhieuDatHang();
                        ResultSet rs=BPD.getChiTietPhieuDatHang(maphieudathang);
                        displayDataChiTietPhieuNhap(rs);
                       System.out.println("Bớt số lượng thành công!");
                   }else
                       System.out.print("Bớt số lượng bị lỗi!");
               }
           }else
               JOptionPane.showMessageDialog(this, "Trừ quá số lượng!", "Không được!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonTruActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
        int index = tableChiTietPhieuDatHang.getSelectedRow();
        if(index>=0){
           DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuDatHang.getModel();
           String malinhkien = model.getValueAt(index, 0).toString();
               int index2 = tablePhieuDatHang.getSelectedRow();
               if(index2>=0){
                   String maphieudathang=lsPDH.get(index2).getMaPhieuDatHang();
                   BPhieuDatHang BPDH = new BPhieuDatHang();
                   if(BPDH.deleteMaLinhKienChiTietPhieuDatHang(maphieudathang, malinhkien)){
                       //reload
                        BPhieuDatHang BPD = new BPhieuDatHang();
                        ResultSet rs=BPD.getChiTietPhieuDatHang(maphieudathang);
                        displayDataChiTietPhieuNhap(rs);
                       System.out.println("Xóa thành công!");
                   }else
                       System.out.print("Xóa bị lỗi!");
               }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXActionPerformed

    private void ftextMaPhieuDatHangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ftextMaPhieuDatHangInputMethodTextChanged
       // buttonSua.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ftextMaPhieuDatHangInputMethodTextChanged

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        BPhieuDatHang BPDH = new BPhieuDatHang();
        if(radPhieu.isSelected()){            
            ResultSet rs = BPDH.searchAllPhieuDatHang(textTimKiem.getText());
            displayDataPhieuDatHang(rs);
        }else{
            if(tablePhieuDatHang.getSelectedRow()>=0){
                ResultSet rs = BPDH.searchAllChiTietPhieuDatHang(lsPDH.get(tablePhieuDatHang.getSelectedRow()).getMaPhieuDatHang(), textTimKiem.getText());
                displayDataChiTietPhieuNhap(rs);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonTru;
    private javax.swing.JButton buttonX;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JComboBox combMaLinhKien;
    private javax.swing.JComboBox combNhaCungCap;
    private javax.swing.JComboBox combTenNhanVien;
    private javax.swing.JFormattedTextField ftextMaPhieuDatHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTenPhieu;
    private javax.swing.JRadioButton radChiTietPhieu;
    private javax.swing.JRadioButton radPhieu;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tableChiTietPhieuDatHang;
    private javax.swing.JTable tablePhieuDatHang;
    private javax.swing.JTextField textNgayLapPhieu;
    private javax.swing.JTextField textTimKiem;
    // End of variables declaration//GEN-END:variables
}
