/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Bussiness.BNhanVien;
import Bussiness.BPhieuDatHang;
import Bussiness.BPhieuNhap;
import Item.itemPhieuNhap;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lvdinh
 */
public class inFormPhieuNhap extends javax.swing.JInternalFrame {

    /**
     * Creates new form inFormPhieuNhap
     */
    ArrayList<itemPhieuNhap> lsPN=new ArrayList<>();
    ArrayList<String> lsCombNhanVien=new ArrayList<>();
     ArrayList<String> lsCombPhieuDatHang=new ArrayList<>();
     ArrayList<String> lsCombMaLinhKien=new ArrayList<>();
    public inFormPhieuNhap() {
        initComponents();
        loadComNhanVien();
        loadComPhieuDatHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuNhap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChiTietPhieuNhap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftextMaPhieuNhap = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        combMaPhieuDatHang = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftextNgayLapPhieu = new javax.swing.JFormattedTextField();
        buttonLamMoi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        combTenNhanVien = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        combMaLinhKien = new javax.swing.JComboBox();
        buttonCong = new javax.swing.JButton();

        setClosable(true);
        setTitle("Phiếu nhập");
        setName("PhieuNhap"); // NOI18N

        tablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã phiếu đặt hàng", "Nhà cung cấp", "Tên nhân viên", "Ngày lập phiếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuNhap);

        tableChiTietPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã linh kiện", "Tên linh kiện", "Số lượng đã đặt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableChiTietPhieuNhap);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chi tiết phiếu nhập");

        jLabel2.setText("Mã phiếu nhập");

        try {
            ftextMaPhieuNhap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("PN####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Mã phiếu đặt hàng");

        jLabel4.setText("Tên nhân viên");

        jLabel5.setText("Ngày lập phiếu");

        ftextNgayLapPhieu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));

        buttonLamMoi.setText("Làm mới");
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        jButton2.setText("Tìm kiếm");

        jLabel6.setText("Tìm kiếm");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Phiếu nhập");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Chi tiết phiếu nhập");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sửa");

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Xóa");

        jLabel7.setText("Mã linh kiện");

        buttonCong.setText("+");
        buttonCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(combMaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCong)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftextMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftextNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combMaPhieuDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButton2))
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonLamMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftextMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combMaPhieuDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftextNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel7)
                    .addComponent(combMaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCong))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayDataPhieuNhap(ResultSet rs){
        lsPN.clear();
        DefaultTableModel model = (DefaultTableModel) tablePhieuNhap.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                itemPhieuNhap item = new itemPhieuNhap(rs.getString("MaPhieuNhap"), rs.getString("MaPhieuDatHang"),
                         rs.getString("TenNhaCungcap"),rs.getString("TenNhanvienLapPhieuNhap"), rs.getString("NgayLapPhieuNhap"));
                lsPN.add(item);
                
                Vector vector = new Vector();
                vector.add(item.getMaPhieuNhap());
                vector.add(item.getMaPhieuDatHang());
                
                vector.add(item.getTenNhaCungCap());
                vector.add(item.getTenNhanVienLapPhieuNhap());
                vector.add(item.getNgayLapPhieuNhap());
                
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataPhieuNhap: " + ex.getMessage());
        }
    }
    private void displayDataChiTietPhieuNhap(ResultSet rs){
        DefaultTableModel model = (DefaultTableModel) tableChiTietPhieuNhap.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {

            while (rs.next()) {
                
                Vector vector = new Vector();
                
                vector.add(rs.getString("MaLinhKien"));
                vector.add(rs.getString("TenLinhKien"));
                vector.add(rs.getString("SoLuong"));
                
                model.addRow(vector);

            }
        } catch (Exception ex) {
            System.out.printf("Ngoại lệ tại displayDataChiTietPhieuNhap: " + ex.getMessage());
        }
    }
    private void loadCombMaLinhKien(String s){
        lsCombMaLinhKien.clear();
        combMaLinhKien.removeAllItems();
        BPhieuDatHang BPDH = new BPhieuDatHang();
        ResultSet rs=BPDH.getAllMaLinhKienPhieuDatHang(s);
        try {
            while(rs.next()){
                lsCombMaLinhKien.add(rs.getString("TenLinhKien"));
                combMaLinhKien.addItem(rs.getString("MaLinhKien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadComPhieuDatHang(){
        lsCombPhieuDatHang.clear();
        combMaPhieuDatHang.removeAllItems();
        BPhieuDatHang BPDH=new BPhieuDatHang();
        ResultSet rs=BPDH.getAllPhieuDatHangNative();
        try {
            while(rs.next()){
                lsCombPhieuDatHang.add(rs.getString("MaPhieuDatHang"));
                combMaPhieuDatHang.addItem(rs.getString("MaPhieuDatHang"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadComNhanVien(){
         combTenNhanVien.removeAllItems();
        lsCombNhanVien.clear();
        BNhanVien BNV = new BNhanVien();
        ResultSet rs = BNV.getAllNhanVienXN();
        try {
            while(rs.next()){
                combTenNhanVien.addItem(rs.getString("TenNhanVien"));
                lsCombNhanVien.add(rs.getString("MaNhanVien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormPhieuDatHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        BPhieuNhap BPN=new BPhieuNhap();
        ResultSet rs=BPN.getAll();
        displayDataPhieuNhap(rs);
        loadComNhanVien();
        loadComPhieuDatHang();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLamMoiActionPerformed

    private void tablePhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuNhapMouseClicked
        int index=tablePhieuNhap.getSelectedRow();
        
        String maphieunhap=lsPN.get(index).getMaPhieuNhap();
        String maphieudathang = lsCombPhieuDatHang.get(index);
        loadCombMaLinhKien(maphieudathang);
        
        BPhieuNhap BPN=new BPhieuNhap();
        ResultSet rs=BPN.getChiTietPhieuNhap(maphieunhap);
        displayDataChiTietPhieuNhap(rs);
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePhieuNhapMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BPhieuNhap BPN = new BPhieuNhap();
        if(BPN.insertByProperties( combMaPhieuDatHang.getSelectedItem().toString(),ftextMaPhieuNhap.getText(),
                lsCombNhanVien.get(combTenNhanVien.getSelectedIndex()), ftextNgayLapPhieu.getText())){
            buttonLamMoiActionPerformed(evt);
            //JOptionPane.showMessageDialog(this, "Thêm thành công!", "Đã thêm", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCongActionPerformed
        int index = tablePhieuNhap.getSelectedRow();
        if(index>=0){
            String maphieunhap=lsPN.get(index).getMaPhieuNhap();
            String malinhkien=combMaLinhKien.getSelectedItem().toString();
            String maphieudathang = lsCombPhieuDatHang.get(index);
            BPhieuNhap BPN=new BPhieuNhap();
            if(BPN.insertChiTietPhieuNhap2(maphieunhap, maphieudathang, malinhkien)){
                buttonLamMoiActionPerformed(evt);
                ResultSet rs=BPN.getChiTietPhieuNhap(maphieunhap);
                displayDataChiTietPhieuNhap(rs);
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi khi thêm!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JComboBox combMaLinhKien;
    private javax.swing.JComboBox combMaPhieuDatHang;
    private javax.swing.JComboBox combTenNhanVien;
    private javax.swing.JFormattedTextField ftextMaPhieuNhap;
    private javax.swing.JFormattedTextField ftextNgayLapPhieu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableChiTietPhieuNhap;
    private javax.swing.JTable tablePhieuNhap;
    // End of variables declaration//GEN-END:variables
}
