/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Bussiness.BLoaiLinhKien;
import Bussiness.BSanPham;
import Item.itemSanPham;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lvdinh
 */
public class inFormSanPham extends javax.swing.JInternalFrame {

    /**
     * Creates new form inFormLinhKien
     */
    String imagePath="src/images/none.jpg";
    
    ArrayList<itemSanPham> lsSP = new ArrayList<>();    
    ArrayList<String> listCombLoaiLinhKien = new ArrayList<>();
    ArrayList<String> listCombDonViTinh = new ArrayList<>();
    ArrayList<String> listCombMaPhieuNhap = new ArrayList<>();
    ArrayList<String> listCombMaLinhKien = new ArrayList<>();
    int[] arrayTimKiem = new int[9];
    ImageIcon icon;
    String imageLocation="d:\\pictures\\laptop\\";
    String imageName;
    
    public inFormSanPham() {
        initComponents();
        
        
        icon=new ImageIcon("d:\\pictures\\laptop\\"+imagePath);
       
        labelHinhAnh.setIcon(icon);
        labelHinhAnh.setSize(100,100);
        
        
        textTimKiem.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                //System.out.println("removeUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                //System.out.println("insertUpdate");
                buttonTimKiemActionPerformed(null);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //System.out.println("changedUpdate");
                buttonTimKiemActionPerformed(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textTimKiem = new javax.swing.JTextField();
        buttonTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelHinhAnh = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/images/none.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        labelHinhAnh = new javax.swing.JLabel();
        combTenLoaiLinhKien = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textTenLinhkien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMoTaLinhKien = new javax.swing.JTextArea();
        buttonDoiHinh = new javax.swing.JButton();
        buttonXoaTruong = new javax.swing.JButton();
        buttonLuu = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        buttonThem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spinThoiGianBaoHanh = new javax.swing.JSpinner();
        combDonViTinh = new javax.swing.JComboBox();
        buttonLamMoi = new javax.swing.JButton();
        checkLoaiLinhKien = new javax.swing.JCheckBox();
        checkMaLinhKien = new javax.swing.JCheckBox();
        checkTenLinhKien = new javax.swing.JCheckBox();
        checkHangSanXuat = new javax.swing.JCheckBox();
        checkDonViTinh = new javax.swing.JCheckBox();
        checkThoiGianBaoHanh = new javax.swing.JCheckBox();
        checkSoLuongTon = new javax.swing.JCheckBox();
        checkMoTa = new javax.swing.JCheckBox();
        checkTatCa = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        combMaPhieuNhap = new javax.swing.JComboBox();
        checkMaPhieuNhap = new javax.swing.JCheckBox();
        combMaLinhKien = new javax.swing.JComboBox();
        spinSoLuongTon = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sản phẩm");
        setName("SanPham"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Loại linh kiện", "Mã linh kiện", "Tên linh kiện", "Hãng sản xuất", "Đơn vị tính", "Thời gian bảo hành", "Số lượng tồn", "Mô tả linh kiện"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        tableSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        jLabel1.setText("Tìm kiếm");

        textTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTimKiemKeyPressed(evt);
            }
        });

        buttonTimKiem.setText("Tìm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Theo");

        labelHinhAnh.setMaximumSize(new java.awt.Dimension(300, 202));
        labelHinhAnh.setMinimumSize(new java.awt.Dimension(300, 202));

        javax.swing.GroupLayout panelHinhAnhLayout = new javax.swing.GroupLayout(panelHinhAnh);
        panelHinhAnh.setLayout(panelHinhAnhLayout);
        panelHinhAnhLayout.setHorizontalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelHinhAnhLayout.setVerticalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHinhAnhLayout.createSequentialGroup()
                .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        combTenLoaiLinhKien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combTenLoaiLinhKien.setEnabled(false);

        jLabel3.setText("Loại linh kiện");

        jLabel4.setText("Mã linh kiện");

        jLabel5.setText("Tên linh kiện");

        jLabel6.setText("Đơn vị tính");

        jLabel7.setText("Thời gian bảo hành");

        jLabel8.setText("Số lượng tồn");

        jLabel9.setText("Mô tả linh kiện");

        textTenLinhkien.setEnabled(false);

        textMoTaLinhKien.setColumns(20);
        textMoTaLinhKien.setRows(5);
        textMoTaLinhKien.setEnabled(false);
        jScrollPane2.setViewportView(textMoTaLinhKien);

        buttonDoiHinh.setText("Đổi hình...");
        buttonDoiHinh.setEnabled(false);
        buttonDoiHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoiHinhActionPerformed(evt);
            }
        });

        buttonXoaTruong.setText("Xóa trường");
        buttonXoaTruong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaTruongActionPerformed(evt);
            }
        });

        buttonLuu.setText("Lưu");
        buttonLuu.setEnabled(false);
        buttonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuActionPerformed(evt);
            }
        });

        buttonSua.setText("Sửa");
        buttonSua.setActionCommand("Sua");
        buttonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaActionPerformed(evt);
            }
        });

        buttonThem.setText("Thêm");
        buttonThem.setActionCommand("Them");
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });

        jLabel10.setText("tháng");

        spinThoiGianBaoHanh.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinThoiGianBaoHanh.setEnabled(false);

        combDonViTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combDonViTinh.setEnabled(false);
        combDonViTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combDonViTinhActionPerformed(evt);
            }
        });

        buttonLamMoi.setText("Làm mới");
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        checkLoaiLinhKien.setText("Loại linh kiện");
        checkLoaiLinhKien.setName("0"); // NOI18N
        checkLoaiLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkLoaiLinhKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkMaLinhKien.setText("Mã linh kiện");
        checkMaLinhKien.setName("1"); // NOI18N
        checkMaLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkMaLinhKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkTenLinhKien.setText("Tên linh kiện");
        checkTenLinhKien.setName("2"); // NOI18N
        checkTenLinhKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkTenLinhKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkHangSanXuat.setText("Hãng sản xuất");
        checkHangSanXuat.setName("3"); // NOI18N
        checkHangSanXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkHangSanXuat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkDonViTinh.setText("Đơn vị tính");
        checkDonViTinh.setName("4"); // NOI18N
        checkDonViTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkDonViTinh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkThoiGianBaoHanh.setText("Thời gian bảo hành");
        checkThoiGianBaoHanh.setName("5"); // NOI18N
        checkThoiGianBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkThoiGianBaoHanh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkSoLuongTon.setText("Số lượng tồn");
        checkSoLuongTon.setName("6"); // NOI18N
        checkSoLuongTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkSoLuongTon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkMoTa.setText("Mô tả linh kiện");
        checkMoTa.setName("7"); // NOI18N
        checkMoTa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkMoTa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        checkTatCa.setText("Tìm theo tất cả");
        checkTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTatCaMouseClicked(evt);
            }
        });

        jLabel11.setText("Mã phiếu nhập");

        combMaPhieuNhap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combMaPhieuNhap.setEnabled(false);
        combMaPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combMaPhieuNhapMouseClicked(evt);
            }
        });

        checkMaPhieuNhap.setText("Mã phiếu nhập");
        checkMaPhieuNhap.setName("8"); // NOI18N
        checkMaPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHangSanXuatMouseClicked(evt);
            }
        });
        checkMaPhieuNhap.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkHangSanXuatStateChanged(evt);
            }
        });

        combMaLinhKien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combMaLinhKien.setEnabled(false);

        spinSoLuongTon.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        spinSoLuongTon.setForeground(new java.awt.Color(0, 0, 204));
        spinSoLuongTon.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(checkLoaiLinhKien)
                                .addGap(18, 18, 18)
                                .addComponent(checkMaLinhKien)
                                .addGap(18, 18, 18)
                                .addComponent(checkTenLinhKien)
                                .addGap(18, 18, 18)
                                .addComponent(checkHangSanXuat)
                                .addGap(18, 18, 18)
                                .addComponent(checkDonViTinh)
                                .addGap(18, 18, 18)
                                .addComponent(checkThoiGianBaoHanh)
                                .addGap(18, 18, 18)
                                .addComponent(checkSoLuongTon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkTatCa)
                                .addGap(18, 18, 18)
                                .addComponent(checkMoTa)
                                .addGap(18, 18, 18)
                                .addComponent(checkMaPhieuNhap)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(panelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonLuu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(spinThoiGianBaoHanh)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10))
                                            .addComponent(spinSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combTenLoaiLinhKien, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textTenLinhkien)
                                            .addComponent(combDonViTinh, 0, 175, Short.MAX_VALUE)
                                            .addComponent(combMaPhieuNhap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(combMaLinhKien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(buttonXoaTruong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttonDoiHinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(combMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDoiHinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combMaLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combTenLoaiLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTenLinhkien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonXoaTruong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(spinThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(buttonSua)
                    .addComponent(spinSoLuongTon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonThem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonTimKiem)
                        .addComponent(checkTatCa)
                        .addComponent(checkMoTa)
                        .addComponent(buttonLamMoi)
                        .addComponent(checkMaPhieuNhap)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLoaiLinhKien)
                    .addComponent(jLabel2)
                    .addComponent(checkMaLinhKien)
                    .addComponent(checkTenLinhKien)
                    .addComponent(checkHangSanXuat)
                    .addComponent(checkDonViTinh)
                    .addComponent(checkThoiGianBaoHanh)
                    .addComponent(checkSoLuongTon))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void displayData(ResultSet rs) {

            lsSP.clear();
            DefaultTableModel model;
            model = (DefaultTableModel) tableSanPham.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            try {
                while (rs.next()) {
                   itemSanPham item = new itemSanPham(rs.getString("MaPhieuNhap"),
                                                    (rs.getString("TenLoaiLinhKien")),
                                                    (rs.getString("MaLinhKien")),
                                                    (rs.getString("TenLinhkien")),
                                                    (rs.getString("TenNhaCungCap")),
                                                    (rs.getString("DonViTinh")),
                                                    (rs.getInt("ThoiGianBaoHanh")),
                                                    (rs.getInt("SoLuongTon")),

                                                    (rs.getString("MoTaLinhKien")),
                                                    (rs.getString("HinhAnh")));
                   
                    lsSP.add(item);


                    Vector vector = new Vector();
                    
                    vector.add(item.getMaPhieuNhap());
                    vector.add(item.getTenLoaiLinhKien());
                    vector.add(item.getMaLinhKien());
                    
                    vector.add(item.getTenLinhKien());

                    vector.add(item.getTenNhaCungCap());
                    vector.add(item.getDonViTinh());
                    vector.add(item.getThoiGianBaoHanh());
                    vector.add(item.getSoLuongTon());
                    
                    vector.add(item.getMoTaLinhKien());
                   // vector.add(rs.getString("HinhAnh"));
                    
                    model.addRow(vector);

//                model.addRow(new Object[]{item.getID(),item.getName(),gioitinh,
//                        item.getBirthday(),item.getAddress(),item.getPhone(),item.getPosition(),item.getOther()});
                }
            } catch (Exception ex) {
                System.out.printf("[Ngoại lệ displayData] " + ex.getMessage());
            }
            System.out.println("Rows loaded: " + lsSP.toArray().length);
    }
private void loadComboLoaiLinhKien(){
    listCombLoaiLinhKien.clear();
   // listCombLoaiLinhKien.add("");
    combTenLoaiLinhKien.removeAllItems();
   // combMaLoaiLinhKien.addItem("");
    BLoaiLinhKien BLLK = new BLoaiLinhKien();
            ResultSet rs = BLLK.getAllTenLoaiLinhKien();
            try {
                while(rs.next()){
                combTenLoaiLinhKien.addItem(rs.getString("TenLoaiLinhKien"));
                listCombLoaiLinhKien.add(rs.getString("TenLoaiLinhKien"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(inFormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Lỗi load comboBox mã linh kiện! "+ex.getMessage());  
            }
}
private void loadComboDonViTinh(){
    listCombDonViTinh.clear();
   // listCombDonViTinh.add("");
    combDonViTinh.removeAllItems();
   // combDonViTinh.addItem("");
    BSanPham BSP = new BSanPham();
            ResultSet rs = BSP.getDonViTinh();
            try {
                while(rs.next()){
                combDonViTinh.addItem(rs.getString("DonViTinh"));
                listCombDonViTinh.add(rs.getString("DonViTinh"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(inFormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Lỗi load comboBox đơn vị tính! "+ex.getMessage());  
            }
}
private void loadComboMaPhieuNhap(){
    listCombMaPhieuNhap.clear();
    //listCombMaPhieuNhap.add("");
//    if(combMaPhieuNhap.getItemCount()>1)
     combMaPhieuNhap.removeAllItems();
    //combMaPhieuNhap.addItem("");
    BSanPham BSP = new BSanPham();
            ResultSet rs = BSP.getMaPhieuNhap();
            try {
                while(rs.next()){
                combMaPhieuNhap.addItem(rs.getString("MaPhieuNhap"));
                listCombMaPhieuNhap.add(rs.getString("MaPhieuNhap"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(inFormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Lỗi load comboBox mã phiếu nhập! "+ex.getMessage());  
            }
}
private void loadCombMaLinhKien(){
    String maphieunhap = combMaPhieuNhap.getSelectedItem().toString();
    if(maphieunhap==null || "".equals(maphieunhap)){
        
    }
    listCombMaLinhKien.clear();
    //listCombMaLinhKien.add("");
    combMaLinhKien.removeAllItems();
   // combMaLinhKien.addItem("");
    BSanPham BSP = new BSanPham();
    ResultSet rs= BSP.getMaLinhKienByMaPhieuNhap(maphieunhap);
        try {
            while(rs.next()){
                combMaLinhKien.addItem(rs.getString("MaLinhkien"));
                listCombMaLinhKien.add(rs.getString("MaLinhKien"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(inFormSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void setLabelImage(String imagePath){
    if(imagePath==null){
        imagePath="d:\\pictures\\laptop\\default.jpg";
    }
    BufferedImage img = null;
    try {
        img = ImageIO.read(new File(imagePath));
    } catch (IOException e) {
    }
    icon=new ImageIcon(img); 
    
    labelHinhAnh.setIcon(icon);
}
private void setLabelImage(String imageLocation, String imageName){
    if(imageName==null){
        imageName="default.jpg";
    }
    imageLocation=this.imageLocation;
    BufferedImage img = null;
    try {
        img = ImageIO.read(new File(imageLocation+imageName));
    } catch (IOException e) {
    }
    icon=new ImageIcon(img); 
    
    labelHinhAnh.setIcon(icon);
}
    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        // TODO add your handling code here:
        BSanPham BSP = new BSanPham();
        ResultSet rs=BSP.getAll();
        loadComboMaPhieuNhap();
        loadCombMaLinhKien();
        loadComboLoaiLinhKien();
        loadComboDonViTinh();

        
        displayData(rs);
    }//GEN-LAST:event_buttonLamMoiActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        int index = tableSanPham.getSelectedRow();
       // loadComboMaPhieuNhap();
        combMaPhieuNhap.setSelectedItem(lsSP.get(index).getMaPhieuNhap());
        loadCombMaLinhKien();
        combMaLinhKien.setSelectedIndex(listCombMaLinhKien.indexOf(lsSP.get(index).getMaLinhKien()));
        combTenLoaiLinhKien.setSelectedIndex(listCombLoaiLinhKien.indexOf((lsSP.get(index)).getTenLoaiLinhKien()));
        combDonViTinh.setSelectedIndex(listCombDonViTinh.indexOf(lsSP.get(index).getDonViTinh()));
        

        textTenLinhkien.setText(lsSP.get(index).getTenLinhKien());
        spinSoLuongTon.setText(""+lsSP.get(index).getSoLuongTon());
        textMoTaLinhKien.setText(lsSP.get(index).getMoTaLinhKien());
        

        imagePath=lsSP.get(index).getHinhAnh();
        if(imagePath==null){
            setLabelImage(imageLocation,"default.jpg");
        }
        else if(imagePath.indexOf("\\") <0)
            setLabelImage(imageLocation,imagePath);
        else
            setLabelImage(imagePath);
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void buttonDoiHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoiHinhActionPerformed
        // TODO add your handling code here:
//        //Create a file chooser
    final JFileChooser fc = new JFileChooser();
//        //In response to a button click:
//    int returnVal = fc.showOpenDialog(this);
//    
    if (evt.getSource() == buttonDoiHinh) {
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            imagePath=file.getPath();
            setLabelImage(imagePath);
            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
           // log.append("Open command cancelled by user." + newline);
        }
     }
    }//GEN-LAST:event_buttonDoiHinhActionPerformed

    private void combDonViTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combDonViTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combDonViTinhActionPerformed

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        // TODO add your handling code here:
        BSanPham BSP=new BSanPham();
        ResultSet rs = BSP.searchByProperties(arrayTimKiem, textTimKiem.getText());
        displayData(rs);
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        // TODO add your handling code here:
        if(buttonThem.getActionCommand().equals("Them")){
            combDonViTinh.setEnabled(true);
            combMaLinhKien.setEnabled(true);
            combMaPhieuNhap.setEnabled(true);
            combTenLoaiLinhKien.setEnabled(true);

            textMoTaLinhKien.setEnabled(true);
            textTenLinhkien.setEnabled(true);

            spinThoiGianBaoHanh.setEnabled(true);
               
             buttonDoiHinh.setEnabled(true);
             buttonLuu.setEnabled(true);
             buttonSua.setEnabled(false);
             buttonThem.setActionCommand("Huy");
             buttonThem.setText("Hủy");
             
             //---
             loadComboMaPhieuNhap();
             loadCombMaLinhKien();
             loadComboLoaiLinhKien();
             loadComboDonViTinh();
             
             
             
        }
        else{
            combDonViTinh.setEnabled(false);
            combMaLinhKien.setEnabled(false);
            combMaPhieuNhap.setEnabled(false);
            combTenLoaiLinhKien.setEnabled(false);

            textMoTaLinhKien.setEnabled(false);
            textTenLinhkien.setEnabled(false);

            spinThoiGianBaoHanh.setEnabled(false);
            
            buttonDoiHinh.setEnabled(false);
             buttonLuu.setEnabled(false);
             buttonSua.setEnabled(true);
             buttonThem.setActionCommand("Thêm");
             buttonThem.setText("Thêm");
        }
    }//GEN-LAST:event_buttonThemActionPerformed

    private void buttonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuActionPerformed
        // TODO add your handling code here:
        int index=tableSanPham.getSelectedRow();
        BSanPham BSP=new BSanPham();
        if(BSP.updateByProperties(lsSP.get(index).getMaLinhKien(), textTenLinhkien.getText(),
                combTenLoaiLinhKien.getSelectedItem().toString(), combDonViTinh.getSelectedItem().toString(),
                (int) spinThoiGianBaoHanh.getValue(), textMoTaLinhKien.getText(), imagePath)){
               buttonLamMoiActionPerformed(evt); 
               
                //JOptionPane.showMessageDialog(this, "Cập nhật linh kiện thành công!", "Cập nhật thành công!",JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Có lỗi khi cập nhật linh kiện!", "Chưa cập nhật!",JOptionPane.ERROR_MESSAGE);
        // buttonLuu.setEnabled(false);
         buttonThem.setEnabled(true);
         buttonSua.setEnabled(true);
    }//GEN-LAST:event_buttonLuuActionPerformed

    private void checkTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTatCaMouseClicked
        // TODO add your handling code here:
          if(checkTatCa.isSelected()){
            checkMaLinhKien.setSelected(true);
            checkTenLinhKien.setSelected(true);
            checkLoaiLinhKien.setSelected(true);
            checkDonViTinh.setSelected(true);
            
            checkHangSanXuat.setSelected(true);
            checkMoTa.setSelected(true);
            checkSoLuongTon.setSelected(true);
            checkThoiGianBaoHanh.setSelected(true);
            checkMaPhieuNhap.setSelected(true);
        }
        else{
            checkMaLinhKien.setSelected(false);
            checkTenLinhKien.setSelected(false);
            checkLoaiLinhKien.setSelected(false);
            checkDonViTinh.setSelected(false);
            
            checkHangSanXuat.setSelected(false);
            checkMoTa.setSelected(false);
            checkSoLuongTon.setSelected(false);
            checkThoiGianBaoHanh.setSelected(false);
            checkMaPhieuNhap.setSelected(false);
        }
    }//GEN-LAST:event_checkTatCaMouseClicked

    private void checkHangSanXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkHangSanXuatMouseClicked
        // TODO add your handling code here:
        int index;
        JCheckBox check = (JCheckBox) evt.getSource();
        index= Integer.valueOf(check.getName());
        if(check.isSelected())
            arrayTimKiem[index]=1;
        else
            arrayTimKiem[index]=0;
    }//GEN-LAST:event_checkHangSanXuatMouseClicked

    private void checkHangSanXuatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkHangSanXuatStateChanged
        // TODO add your handling code here:
                int index;
        JCheckBox check = (JCheckBox) evt.getSource();
        index= Integer.valueOf(check.getName());
        if(check.isSelected())
            arrayTimKiem[index]=1;
        else
            arrayTimKiem[index]=0;
    }//GEN-LAST:event_checkHangSanXuatStateChanged

    private void textTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTimKiemKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            buttonTimKiemActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_textTimKiemKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_F5)
            buttonLamMoiActionPerformed(null);
    }//GEN-LAST:event_formKeyPressed

    private void buttonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaActionPerformed
        // TODO add your handling code here:
        if(buttonSua.getActionCommand().equals("Sua")){
            combDonViTinh.setEnabled(true);
            combMaLinhKien.setEnabled(true);
            combMaPhieuNhap.setEnabled(true);
            combTenLoaiLinhKien.setEnabled(true);

            textMoTaLinhKien.setEnabled(true);
            textTenLinhkien.setEnabled(true);

            spinThoiGianBaoHanh.setEnabled(true);

            buttonDoiHinh.setEnabled(true);
             buttonLuu.setEnabled(true);
             buttonThem.setEnabled(false);
             buttonSua.setActionCommand("Huy");
             buttonSua.setText("Hủy");
        }
        else{
            combDonViTinh.setEnabled(false);
            combMaLinhKien.setEnabled(false);
            combMaPhieuNhap.setEnabled(false);
            combTenLoaiLinhKien.setEnabled(false);

            textMoTaLinhKien.setEnabled(false);
            textTenLinhkien.setEnabled(false);

            spinThoiGianBaoHanh.setEnabled(false);

            buttonDoiHinh.setEnabled(false);
             buttonLuu.setEnabled(false);
             buttonThem.setEnabled(true);
             buttonSua.setActionCommand("Sua");
             buttonSua.setText("Sửa");
        }
    }//GEN-LAST:event_buttonSuaActionPerformed

    private void buttonXoaTruongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaTruongActionPerformed
        textMoTaLinhKien.setText("");
        textTenLinhkien.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXoaTruongActionPerformed

    private void combMaPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combMaPhieuNhapMouseClicked
        // TODO add your handling code here:
        loadCombMaLinhKien();
    }//GEN-LAST:event_combMaPhieuNhapMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDoiHinh;
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonXoaTruong;
    private javax.swing.JCheckBox checkDonViTinh;
    private javax.swing.JCheckBox checkHangSanXuat;
    private javax.swing.JCheckBox checkLoaiLinhKien;
    private javax.swing.JCheckBox checkMaLinhKien;
    private javax.swing.JCheckBox checkMaPhieuNhap;
    private javax.swing.JCheckBox checkMoTa;
    private javax.swing.JCheckBox checkSoLuongTon;
    private javax.swing.JCheckBox checkTatCa;
    private javax.swing.JCheckBox checkTenLinhKien;
    private javax.swing.JCheckBox checkThoiGianBaoHanh;
    private javax.swing.JComboBox combDonViTinh;
    private javax.swing.JComboBox combMaLinhKien;
    private javax.swing.JComboBox combMaPhieuNhap;
    private javax.swing.JComboBox combTenLoaiLinhKien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JPanel panelHinhAnh;
    private javax.swing.JLabel spinSoLuongTon;
    private javax.swing.JSpinner spinThoiGianBaoHanh;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextArea textMoTaLinhKien;
    private javax.swing.JTextField textTenLinhkien;
    private javax.swing.JTextField textTimKiem;
    // End of variables declaration//GEN-END:variables
}
